### ISSUE TITLE
Why HMAC digest before crypto.timingSafeEqual?

### ISSUE THREAD

**Issue by victorherraiz-santander** [suryagh/tsscmp#14]
Is there any reason to not call directly to node's method directly with the input? (if both have the same length)

**Comment by suryagh** [comment]
Yes, this is to deterministically randomize. Please refer [here](https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/february/double-hmac-verification/)

**Comment by ghost** [comment]
It would make sense to me to use either `crypto.timingSafeEqual()` or to use HMAC. Either should protect from timing attacks. So why use both?

It seems to me that there was a mistake in https://github.com/suryagh/tsscmp/pull/7, which really should have added the call to `crypto.timingSafeEqual()` to the function `timeSafeCompare()`, not to `bufferEqual()`. The way it is implemented now, the function `bufferEqual()` is either timing-safe or timing-unsafe, depending on what Node.js API is available, and that does not seem right.

The link no longer works, by the way, and even after digging up an old version from the Wayback Machine and reading it, I do not see why you would need an extra layer of randomness on top of an algorithm which is already timing-safe.

Really though, `crypto.timingSafeEqual()` has been available in Node.js for 8 years now, and is now part of every actively supported version. No Internet-facing services should be using unsupported Node.js versions, anyway. Isn't it time to mark this whole package as obsolete?
