### ISSUE TITLE
README on npmjs.org is messed up

### ISSUE THREAD

**Issue by dougwilson** [suryagh/tsscmp#4]
It looks like the Markdown renderer on npmjs.org is slightly different than on GitHub and it does not like something from the readme.

https://www.npmjs.com/package/tsscmp
![image](https://cloud.githubusercontent.com/assets/67512/15458803/7788b45e-206c-11e6-801c-6a2315a3975c.png)

Just a heads-up :)

**Comment by suryagh** [comment]
@dougwilson thank you for the heads-up. I just reported this issue to npmjs.org. 

In addition to github.com, my `vscode ide` is also able to parse the `readme` just fine! :) Something off with the npmjs.org parser.

**Comment by dougwilson** [comment]
No problem :) For a while, we had a similar problem with the `express-session` module, where it worked fine, then suddenly npmjs.org just didn't like it any longer. Eventually npmjs.org fixed it and resolved to parse like GitHub, which is of course the best way to go about it :)

**Comment by dougwilson** [comment]
P.S. I use VS Code and didn't even know it had that preview functionality. That's pretty sweet 🌠

**Comment by suryagh** [comment]
The issue was that npmjs.org parser (`marky-markdown`) does not like following syntax according to the npmjs.org support team:

```
[![Node.js Version][node-version-image]][node-version-url]
```

Resolved after using following syntax:

```
[![Node.js Version](https://img.shields.io/node/v/tsscmp.svg?style=flat-square)](https://nodejs.org/en/download)
```
